package cn.xxjc.com.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.xxjc.com.bean.TableResults;

import cn.xxjc.com.dao.TableResultsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tableResultsDaoConfig;

    private final TableResultsDao tableResultsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tableResultsDaoConfig = daoConfigMap.get(TableResultsDao.class).clone();
        tableResultsDaoConfig.initIdentityScope(type);

        tableResultsDao = new TableResultsDao(tableResultsDaoConfig, this);

        registerDao(TableResults.class, tableResultsDao);
    }
    
    public void clear() {
        tableResultsDaoConfig.clearIdentityScope();
    }

    public TableResultsDao getTableResultsDao() {
        return tableResultsDao;
    }

}
